Clarify "Disable" button as an "Enable" Button
LegoFigure11/RaidCrawler pull request #68
Opened 2023-01-05 00:20 UTC by jnovack

Reverses text/function of the "Disable Filters" button to be an "Enable Filters" button.   Fixes #62

2023-01-05 00:24 UTC, jnovack commented
Function is fundamentally unchanged, just reversed.

![image](https://user-images.githubusercontent.com/387006/210674625-c92c052d-d0e3-47e0-bd15-c119bfbf15bc.png)

2023-01-06 18:22 UTC, architdate requested changes
The default should also be set to true (checked)

2023-01-06 18:22 UTC, architdate commented on MainWindow.cs
> +            if (CheckEnableFilters.Checked)
This condition needs to be inverted if we are to have checkenabledfilters

2023-01-06 20:27 UTC, jnovack commented on MainWindow.cs
> +            if (CheckEnableFilters.Checked)
....aaaand this is why we do code reviews :)

2023-01-07 04:07 UTC, architdate approved these changes

2023-01-07 04:08 UTC, merged

2023-01-07 04:08 UTC, architdate commented
Ty for the edits, merged :)